[features]
strict = []

[package]
name = "rlst-gfortran-src"
version = "0.1.0"
edition = "2021"
links = "gfortran"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "rlst_gfortran_src"

[build-dependencies]


