name: 📖

on:
  push:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "nightly"
      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: "mpich"
      - uses: actions/checkout@v3

      - name: Build docs
        run: RUSTDOCFLAGS="-Zunstable-options" cargo +nightly doc --no-deps -Zunstable-options -Zrustdoc-scrape-examples --features "mpi,strict"

      - name: Set file permissions
        run: |
          rm target/doc/.lock
          chmod -c -R +rX target/doc

      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: github.ref == 'refs/heads/main'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/doc'
        if: github.ref == 'refs/heads/main'

  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

